# Generated by Django 5.2.3 on 2025-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='To‘liq ism')),
                ('role', models.CharField(max_length=100, verbose_name='Lavozimi')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Rasm')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram havolasi')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram havolasi')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn havolasi')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['id'],
            },
        ),
    ]
