# Generated by Django 5.2.3 on 2025-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('images', models.ImageField(upload_to='group/')),
                ('tajriba', models.CharField(max_length=255)),
                ('mutaxasisli', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
