# Generated by Django 5.2.3 on 2025-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyha',
            name='category',
            field=models.CharField(choices=[('website', 'Veb sayt'), ('design', 'Veb dizayn'), ('smm', 'SMM'), ('mobile', 'Mobil ilova')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyha',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loyha',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
