# Generated by Django 5.2.3 on 2025-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyha', '0002_loyha_category_alter_loyha_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyha',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
