# Generated by Django 5.2.3 on 2025-06-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyha', '0003_alter_loyha_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyha',
            name='category',
        ),
    ]
