# Generated by Django 5.2.3 on 2025-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyha', '0004_remove_loyha_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyha',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
